{
  "domain": "lueftung",
  "name": "Lüftungssteuerung",
  "version": "2.0.0",
  "issue_tracker": "https://github.com/DEIN_GITHUB_NAME/ha-lueftung/issues",
  "documentation": "",
  "requirements": [],
  "dependencies": [],
  "codeowners": [],
  "iot_class": "cloud_polling",
  "config_flow": true
}
